// AUTO-GENERATED by scripts/build-edgeone.js —— 勿手动修改
// EdgeOne Makers 云函数只打包 cloud-functions/ 目录，本文件自包含 server/dataStore/npc 价格
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);

// 复用 serverless 守卫：跳过 app.listen 和后台定时任务（server/index.js 检查该变量）
process.env.IS_FC = '1';

const path = require('path');
const express = require('express');
const axios = require('axios');
const cors = require('cors');
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---- dataStore（内联，含只读文件系统内存兜底）----
const dataStore = (() => {
  const module = { exports: {} };
const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'data');
const HISTORY_FILE = path.join(DATA_DIR, 'history.json');
const FAVORITES_FILE = path.join(DATA_DIR, 'favorites.json');

// 内存兜底：serverless 平台（如 Vercel）文件系统只读，写文件会失败时降级到内存
const memoryStore = {
  history: {},
  favorites: []
};
let readOnly = false;

function initFiles() {
  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    if (!fs.existsSync(HISTORY_FILE)) fs.writeFileSync(HISTORY_FILE, JSON.stringify({}));
    if (!fs.existsSync(FAVORITES_FILE)) fs.writeFileSync(FAVORITES_FILE, JSON.stringify([]));
    readOnly = false;
  } catch (error) {
    readOnly = true;
    console.warn('File storage unavailable, using in-memory fallback:', error.message);
  }

  // 读入内存，保证内存与文件一致
  try {
    memoryStore.history = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'));
  } catch {
    memoryStore.history = {};
  }
  try {
    memoryStore.favorites = JSON.parse(fs.readFileSync(FAVORITES_FILE, 'utf8'));
  } catch {
    memoryStore.favorites = [];
  }
}
initFiles();

/**
 * Get history data for a specific product
 * @param {string} productId - The product ID
 * @returns {Array} Array of historical price points
 */
function getHistory(productId) {
  return memoryStore.history[productId] || [];
}

/**
 * Save price data to history
 * @param {string} productId - The product ID
 * @param {Object} priceData - Current price data
 */
function saveToHistory(productId, priceData) {
  try {
    if (!memoryStore.history[productId]) {
      memoryStore.history[productId] = [];
    }

    const timestamp = new Date().toISOString();
    memoryStore.history[productId].push({
      timestamp,
      buyPrice: priceData.buyPrice,
      sellPrice: priceData.sellPrice,
      buyOrders: priceData.buyOrders,
      sellOrders: priceData.sellOrders
    });

    // Keep only last 30 days of data (assuming updates every few minutes)
    const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000);
    memoryStore.history[productId] = memoryStore.history[productId].filter(entry => {
      return new Date(entry.timestamp).getTime() > thirtyDaysAgo;
    });

    if (!readOnly) {
      fs.writeFileSync(HISTORY_FILE, JSON.stringify(memoryStore.history, null, 2));
    }
  } catch (error) {
    console.error('Error saving to history:', error.message);
  }
}

/**
 * Get all favorites
 * @returns {Array} Array of favorite product IDs
 */
function getFavorites() {
  return memoryStore.favorites;
}

/**
 * Add a product to favorites
 * @param {string} productId - The product ID to add
 */
function addFavorite(productId) {
  try {
    if (!memoryStore.favorites.includes(productId)) {
      memoryStore.favorites.push(productId);
      if (!readOnly) {
        fs.writeFileSync(FAVORITES_FILE, JSON.stringify(memoryStore.favorites, null, 2));
      }
    }
    return memoryStore.favorites;
  } catch (error) {
    console.error('Error adding favorite:', error.message);
    return memoryStore.favorites;
  }
}

/**
 * Remove a product from favorites
 * @param {string} productId - The product ID to remove
 */
function removeFavorite(productId) {
  try {
    memoryStore.favorites = memoryStore.favorites.filter(f => f !== productId);
    if (!readOnly) {
      fs.writeFileSync(FAVORITES_FILE, JSON.stringify(memoryStore.favorites, null, 2));
    }
    return memoryStore.favorites;
  } catch (error) {
    console.error('Error removing favorite:', error.message);
    return memoryStore.favorites;
  }
}

/**
 * Get all history data for export
 * @returns {Object} All historical data
 */
function getAllHistory() {
  return memoryStore.history;
}

/**
 * Export history as CSV format
 * @returns {string} CSV formatted string
 */
function exportAsCSV() {
  const history = getAllHistory();
  let csv = 'Product ID,Timestamp,Buy Price,Sell Price,Buy Orders,Sell Orders\n';

  for (const [productId, entries] of Object.entries(history)) {
    for (const entry of entries) {
      csv += `${productId},${entry.timestamp},${entry.buyPrice},${entry.sellPrice},${entry.buyOrders},${entry.sellOrders}\n`;
    }
  }

  return csv;
}

module.exports = {
  getHistory,
  saveToHistory,
  getFavorites,
  addFavorite,
  removeFavorite,
  getAllHistory,
  exportAsCSV
};

  return module.exports;
})();

// ---- NPC 价格（内联自 data/npc-prices.json）----
const npcPrices = {
  "ROTTEN_FLESH": {
    "perUnit": 8,
    "npc": "ADVENTURER"
  },
  "BONE": {
    "perUnit": 8,
    "npc": "ADVENTURER"
  },
  "STRING": {
    "perUnit": 10,
    "npc": "ADVENTURER"
  },
  "SLIME_BALL": {
    "perUnit": 14,
    "npc": "ADVENTURER"
  },
  "SULPHUR": {
    "perUnit": 10,
    "npc": "ADVENTURER"
  },
  "ZOMBIE_TALISMAN": {
    "perUnit": 500,
    "npc": "ADVENTURER"
  },
  "SKELETON_TALISMAN": {
    "perUnit": 500,
    "npc": "ADVENTURER"
  },
  "VILLAGE_TALISMAN": {
    "perUnit": 2500,
    "npc": "ADVENTURER"
  },
  "MINE_TALISMAN": {
    "perUnit": 2500,
    "npc": "ADVENTURER"
  },
  "INTIMIDATION_TALISMAN": {
    "perUnit": 10000,
    "npc": "ADVENTURER"
  },
  "SCAVENGER_TALISMAN": {
    "perUnit": 10000,
    "npc": "ADVENTURER"
  },
  "BEGINNER_COMBAT_SACK": {
    "perUnit": 250,
    "npc": "ADVENTURER"
  },
  "NETHER_STALK": {
    "perUnit": 10,
    "npc": "AN"
  },
  "BREWING_STAND_ITEM": {
    "perUnit": 30,
    "npc": "ALCHEMIST"
  },
  "GLASS_BOTTLE": {
    "perUnit": 6.25,
    "npc": "ALCHEMIST"
  },
  "POTION": {
    "perUnit": 6,
    "npc": "ALCHEMIST"
  },
  "SUGAR": {
    "perUnit": 4,
    "npc": "ALCHEMIST"
  },
  "RABBIT_FOOT": {
    "perUnit": 10,
    "npc": "ALCHEMIST"
  },
  "SPECKLED_MELON": {
    "perUnit": 10,
    "npc": "ALCHEMIST"
  },
  "SPIDER_EYE": {
    "perUnit": 12,
    "npc": "ALCHEMIST"
  },
  "BLAZE_POWDER": {
    "perUnit": 12,
    "npc": "ALCHEMIST"
  },
  "GHAST_TEAR": {
    "perUnit": 200,
    "npc": "ALCHEMIST"
  },
  "MAGMA_CREAM": {
    "perUnit": 20,
    "npc": "ALCHEMIST"
  },
  "GOLDEN_CARROT": {
    "perUnit": 30,
    "npc": "ALCHEMIST"
  },
  "ABIPHONE_BASIC": {
    "perUnit": 5000,
    "npc": "ALDA"
  },
  "SERIOUSLY_DAMAGED_AXE": {
    "perUnit": 5000,
    "npc": "AMAURY"
  },
  "DECENT_AXE": {
    "perUnit": 1000000,
    "npc": "AMAURY"
  },
  "CANOPY_HELMET": {
    "perUnit": 116400,
    "npc": "AMAURY"
  },
  "CANOPY_CHESTPLATE": {
    "perUnit": 135800,
    "npc": "AMAURY"
  },
  "CANOPY_LEGGINGS": {
    "perUnit": 126100,
    "npc": "AMAURY"
  },
  "CANOPY_BOOTS": {
    "perUnit": 106700,
    "npc": "AMAURY"
  },
  "SAND-1": {
    "perUnit": 20,
    "npc": "AN"
  },
  "BLAZE_ROD": {
    "perUnit": 50,
    "npc": "AN"
  },
  "QUARTZ": {
    "perUnit": 50,
    "npc": "AN"
  },
  "PARKOUR_CONTROLLER": {
    "perUnit": 1000,
    "npc": "AMELIA"
  },
  "PARKOUR_POINT": {
    "perUnit": 1000,
    "npc": "AMELIA"
  },
  "PARKOUR_TIMES": {
    "perUnit": 2000,
    "npc": "AMELIA"
  },
  "SOCIAL_DISPLAY": {
    "perUnit": 10000,
    "npc": "AMELIA"
  },
  "EGG_HUNT": {
    "perUnit": 1000,
    "npc": "AMELIA"
  },
  "ISLAND_NPC": {
    "perUnit": 50000,
    "npc": "AMELIA"
  },
  "TIC_TAC_TOE": {
    "perUnit": 2500,
    "npc": "AMELIA"
  },
  "CONNECT_FOUR": {
    "perUnit": 2500,
    "npc": "AMELIA"
  },
  "ROCK_PAPER_SHEARS": {
    "perUnit": 10000,
    "npc": "AMELIA"
  },
  "SHOWCASE_BLOCK": {
    "perUnit": 50000,
    "npc": "AMELIA"
  },
  "NEW_YEAR_CAKE_BAG": {
    "perUnit": 250000,
    "npc": "BAKER"
  },
  "THORNLEAF_SCYTHE": {
    "perUnit": 100000,
    "npc": "BARBARIAN_EMISSARY"
  },
  "CHEAP_COFFEE": {
    "perUnit": 1000,
    "npc": "BARTENDER"
  },
  "TEPID_GREEN_TEA": {
    "perUnit": 1000,
    "npc": "BARTENDER"
  },
  "PULPOUS_ORANGE_JUICE": {
    "perUnit": 1000,
    "npc": "BARTENDER"
  },
  "BITTER_ICE_TEA": {
    "perUnit": 1200,
    "npc": "BARTENDER"
  },
  "KNOCKOFF_COLA": {
    "perUnit": 1500,
    "npc": "BARTENDER"
  },
  "DECENT_COFFEE": {
    "perUnit": 5000,
    "npc": "BARTENDER"
  },
  "WOLF_FUR_MIXIN": {
    "perUnit": 150000,
    "npc": "BARTENDER"
  },
  "SPIDER_EGG_MIXIN": {
    "perUnit": 150000,
    "npc": "BARTENDER"
  },
  "ZOMBIE_BRAIN_MIXIN": {
    "perUnit": 150000,
    "npc": "BARTENDER"
  },
  "END_PORTAL_FUMES_MIXIN": {
    "perUnit": 150000,
    "npc": "BARTENDER"
  },
  "GABAGOEY_MIXIN": {
    "perUnit": 150000,
    "npc": "BARTENDER"
  },
  "SMALL_HONEY_DIPPER": {
    "perUnit": 500,
    "npc": "BEA"
  },
  "MEDIUM_HONEY_DIPPER": {
    "perUnit": 5000,
    "npc": "BEA"
  },
  "LARGE_HONEY_DIPPER": {
    "perUnit": 50000,
    "npc": "BEA"
  },
  "GIANT_HONEY_DIPPER": {
    "perUnit": 500000,
    "npc": "BEA"
  },
  "MINING_PUMPKIN": {
    "perUnit": 50000,
    "npc": "BRYNMOR"
  },
  "FILET_O_FORTUNE": {
    "perUnit": 100000,
    "npc": "BRYNMOR"
  },
  "CHILLED_PRISTINE_POTATO": {
    "perUnit": 250000,
    "npc": "BRYNMOR"
  },
  "FRACTURED_MITHRIL_PICKAXE": {
    "perUnit": 10000,
    "npc": "BUBU"
  },
  "BIOFUEL": {
    "perUnit": 20000,
    "npc": "BUBU"
  },
  "RUSTY_TITANIUM_PICKAXE": {
    "perUnit": 50000,
    "npc": "BUBU"
  },
  "SCARECROW": {
    "perUnit": 120,
    "npc": "CARPENTER"
  },
  "WEAPON_RACK": {
    "perUnit": 100,
    "npc": "CARPENTER"
  },
  "ARMOR_SHOWCASE": {
    "perUnit": 100,
    "npc": "CARPENTER"
  },
  "FANCY_FLOWER_POT": {
    "perUnit": 150,
    "npc": "CARPENTER"
  },
  "ENCHANTING_PLUS": {
    "perUnit": 10000,
    "npc": "CARPENTER"
  },
  "CRAFTING_PLUS": {
    "perUnit": 10000,
    "npc": "CARPENTER"
  },
  "FURNACE_PLUS": {
    "perUnit": 15000,
    "npc": "CARPENTER"
  },
  "WOOD_CHEST": {
    "perUnit": 15000,
    "npc": "CARPENTER"
  },
  "FIREPLACE": {
    "perUnit": 10000,
    "npc": "CARPENTER"
  },
  "CHEST_SHELVES": {
    "perUnit": 15000,
    "npc": "CARPENTER"
  },
  "MOODY_GRAPPLESHOT": {
    "perUnit": 3700000,
    "npc": "DESPERATE_ENGINEER"
  },
  "HUNTING_TOOLKIT": {
    "perUnit": 1000000,
    "npc": "DAVID_HUNTERBOROUGH"
  },
  "PET_ITEM_FARMING_SKILL_BOOST_EPIC": {
    "perUnit": 1500000,
    "npc": "DUNCAN"
  },
  "WHEAT": {
    "perUnit": 2.33,
    "npc": "FARM_MERCHANT"
  },
  "CARROT_ITEM": {
    "perUnit": 2.33,
    "npc": "FARM_MERCHANT"
  },
  "POTATO_ITEM": {
    "perUnit": 2.33,
    "npc": "FARM_MERCHANT"
  },
  "MELON": {
    "perUnit": 2,
    "npc": "FARM_MERCHANT"
  },
  "SUGAR_CANE": {
    "perUnit": 5,
    "npc": "FARM_MERCHANT"
  },
  "PUMPKIN": {
    "perUnit": 8,
    "npc": "FARM_MERCHANT"
  },
  "COCOA": {
    "perUnit": 7,
    "npc": "FARM_MERCHANT"
  },
  "RED_MUSHROOM": {
    "perUnit": 12,
    "npc": "FARM_MERCHANT"
  },
  "BROWN_MUSHROOM": {
    "perUnit": 12,
    "npc": "FARM_MERCHANT"
  },
  "SAND": {
    "perUnit": 4,
    "npc": "FARM_MERCHANT"
  },
  "CACTUS": {
    "perUnit": 10,
    "npc": "FARM_MERCHANT"
  },
  "ENCHANTED_BONE_MEAL": {
    "perUnit": 6,
    "npc": "FARM_MERCHANT"
  },
  "ROOKIE_HOE": {
    "perUnit": 10,
    "npc": "FARM_MERCHANT"
  },
  "HOT_CHOCOLATE": {
    "perUnit": 70000,
    "npc": "EZEKIEL"
  },
  "BLACK_COFFEE": {
    "perUnit": 50000,
    "npc": "EZEKIEL"
  },
  "FISHING_ROD": {
    "perUnit": 50,
    "npc": "FISH_MERCHANT"
  },
  "DIAMOND_SWORD": {
    "perUnit": 50,
    "npc": "FISH_MERCHANT"
  },
  "MINNOW_BAIT": {
    "perUnit": 15,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_HELMET": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_CHESTPLATE": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_LEGGINGS": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_BOOTS": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_NECKLACE": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_CLOAK": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_BRACELET": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "ANGLER_BELT": {
    "perUnit": 100,
    "npc": "FISH_MERCHANT"
  },
  "RAW_FISH": {
    "perUnit": 10,
    "npc": "FISHING_MERCHANT"
  },
  "GOLD_INGOT": {
    "perUnit": 5.5,
    "npc": "GOLD_FORGER"
  },
  "GOLD_HELMET": {
    "perUnit": 10,
    "npc": "GOLD_FORGER"
  },
  "GOLD_CHESTPLATE": {
    "perUnit": 16,
    "npc": "GOLD_FORGER"
  },
  "GOLD_LEGGINGS": {
    "perUnit": 14,
    "npc": "GOLD_FORGER"
  },
  "GOLD_BOOTS": {
    "perUnit": 9,
    "npc": "GOLD_FORGER"
  },
  "FANCY_SWORD": {
    "perUnit": 80,
    "npc": "GOLD_FORGER"
  },
  "GOLD_SPADE": {
    "perUnit": 10,
    "npc": "GOLD_FORGER"
  },
  "GOLD_PICKAXE": {
    "perUnit": 10,
    "npc": "GOLD_FORGER"
  },
  "GOLD_AXE": {
    "perUnit": 10,
    "npc": "GOLD_FORGER"
  },
  "ARROW": {
    "perUnit": 5,
    "npc": "JAX"
  },
  "DECENT_BOW": {
    "perUnit": 500,
    "npc": "GREGORY"
  },
  "SCORNCLAW_BREW": {
    "perUnit": 2000,
    "npc": "GROG"
  },
  "HUB_WIZARD_TOWER_TRAVEL_SCROLL": {
    "perUnit": 11111,
    "npc": "GRUMBLEFOOT"
  },
  "IRON_INGOT": {
    "perUnit": 5.5,
    "npc": "IRON_FORGER"
  },
  "CHAINMAIL_HELMET": {
    "perUnit": 10,
    "npc": "IRON_FORGER"
  },
  "CHAINMAIL_CHESTPLATE": {
    "perUnit": 16,
    "npc": "IRON_FORGER"
  },
  "CHAINMAIL_LEGGINGS": {
    "perUnit": 14,
    "npc": "IRON_FORGER"
  },
  "CHAINMAIL_BOOTS": {
    "perUnit": 9,
    "npc": "IRON_FORGER"
  },
  "IRON_PICKAXE": {
    "perUnit": 60,
    "npc": "IRON_FORGER"
  },
  "ARROW_SWAPPER": {
    "perUnit": 1000,
    "npc": "JAX"
  },
  "JUNK_SINKER": {
    "perUnit": 9700,
    "npc": "JUNKER_JOEL"
  },
  "VIKING_TEAR": {
    "perUnit": 15000,
    "npc": "JOYFUL_VIKING"
  },
  "PARK_JUNGLE_TRAVEL_SCROLL": {
    "perUnit": 70000,
    "npc": "JOYFUL_VIKING"
  },
  "RAIDER_AXE": {
    "perUnit": 130000,
    "npc": "JOYFUL_VIKING"
  },
  "HARDENED_WOOD": {
    "perUnit": 15000,
    "npc": "JAKE"
  },
  "LUCKY_DICE": {
    "perUnit": 1000000,
    "npc": "JAKE"
  },
  "EXP_BOTTLE": {
    "perUnit": 30,
    "npc": "LIBRARIAN"
  },
  "BOOK": {
    "perUnit": 20,
    "npc": "LIBRARIAN"
  },
  "LOG": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "LOG-2": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "LOG-1": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "LOG_2-1": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "LOG_2": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "LOG-3": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "ROOKIE_AXE": {
    "perUnit": 12,
    "npc": "LUMBER_MERCHANT"
  },
  "PROMISING_AXE": {
    "perUnit": 35,
    "npc": "LUMBER_MERCHANT"
  },
  "DIRT-2": {
    "perUnit": 25,
    "npc": "LUMBER_MERCHANT"
  },
  "SWEET_AXE": {
    "perUnit": 100,
    "npc": "LUMBER_MERCHANT"
  },
  "EFFICIENT_AXE": {
    "perUnit": 100,
    "npc": "LUMBER_MERCHANT"
  },
  "WOOD_SWORD": {
    "perUnit": 5,
    "npc": "LUMBER_MERCHANT"
  },
  "WOOD_PICKAXE": {
    "perUnit": 5,
    "npc": "LUMBER_MERCHANT"
  },
  "WOOD_SPADE": {
    "perUnit": 5,
    "npc": "LUMBER_MERCHANT"
  },
  "WOOD_HOE": {
    "perUnit": 5,
    "npc": "LUMBER_MERCHANT"
  },
  "WOOD_AXE": {
    "perUnit": 5,
    "npc": "LUMBER_MERCHANT"
  },
  "SHADY_RING": {
    "perUnit": 500000,
    "npc": "LUCIUS"
  },
  "TORCH": {
    "perUnit": 0.5,
    "npc": "LUMINA"
  },
  "LANTERN": {
    "perUnit": 10000,
    "npc": "LUMINA"
  },
  "INFINI_TORCH": {
    "perUnit": 100000,
    "npc": "LUMINA"
  },
  "HUB_CASTLE_TRAVEL_SCROLL": {
    "perUnit": 150000,
    "npc": "LONELY_PHILOSOPHER"
  },
  "LAMP_BLACK": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_GRAY": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_LIGHT_GRAY": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_WHITE": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_BROWN": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_ORANGE": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_RED": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_YELLOW": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_PURPLE": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_MAGENTA": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_LILAC": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_PINK": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_GREEN": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_LIME": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_BLUE": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_CYAN": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_LIGHT_BLUE": {
    "perUnit": 150000,
    "npc": "LYS"
  },
  "LAMP_RAINBOW": {
    "perUnit": 250000,
    "npc": "LYS"
  },
  "REDSTONE_TORCH_ON": {
    "perUnit": 2,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "REDSTONE": {
    "perUnit": 4,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "DAYLIGHT_DETECTOR": {
    "perUnit": 18,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "WOOD_PLATE": {
    "perUnit": 2,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "STONE_PLATE": {
    "perUnit": 4,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "IRON_PLATE": {
    "perUnit": 12,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "GOLD_PLATE": {
    "perUnit": 16,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "LEVER": {
    "perUnit": 2,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "REDSTONE_COMPARATOR": {
    "perUnit": 10,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "DIODE": {
    "perUnit": 6,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "TRIPWIRE_HOOK": {
    "perUnit": 4,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "TNT": {
    "perUnit": 50,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "HOPPER": {
    "perUnit": 50,
    "npc": "MAD_REDSTONE_ENGINEER"
  },
  "TACTICIAN_SWORD": {
    "perUnit": 35000,
    "npc": "MASTER_TACTICIAN"
  },
  "SPORE_HARVESTER": {
    "perUnit": 95000,
    "npc": "MAGE_EMISSARY"
  },
  "GRAND_EXP_BOTTLE": {
    "perUnit": 4750,
    "npc": "MAGE_EMISSARY"
  },
  "TITANIC_EXP_BOTTLE": {
    "perUnit": 712500,
    "npc": "MAGE_EMISSARY"
  },
  "COAL": {
    "perUnit": 4,
    "npc": "MINE_MERCHANT"
  },
  "ROOKIE_PICKAXE": {
    "perUnit": 12,
    "npc": "MINE_MERCHANT"
  },
  "PROMISING_PICKAXE": {
    "perUnit": 35,
    "npc": "MINE_MERCHANT"
  },
  "GRAVEL": {
    "perUnit": 4.33,
    "npc": "PAT"
  },
  "COBBLESTONE": {
    "perUnit": 3,
    "npc": "MINE_MERCHANT"
  },
  "STONE": {
    "perUnit": 2,
    "npc": "MINE_MERCHANT"
  },
  "ONYX": {
    "perUnit": 100,
    "npc": "MINE_MERCHANT"
  },
  "SNORKELING_HELMET": {
    "perUnit": 48500,
    "npc": "NEMO"
  },
  "SNORKELING_CHESTPLATE": {
    "perUnit": 77600,
    "npc": "NEMO"
  },
  "SNORKELING_LEGGINGS": {
    "perUnit": 67900,
    "npc": "NEMO"
  },
  "SNORKELING_BOOTS": {
    "perUnit": 38800,
    "npc": "NEMO"
  },
  "ODGERS_BRONZE_TOOTH": {
    "perUnit": 100000,
    "npc": "ODGER"
  },
  "BRONZE_HUNTER_HELMET": {
    "perUnit": 100000,
    "npc": "ODGER"
  },
  "BRONZE_HUNTER_CHESTPLATE": {
    "perUnit": 100000,
    "npc": "ODGER"
  },
  "BRONZE_HUNTER_LEGGINGS": {
    "perUnit": 100000,
    "npc": "ODGER"
  },
  "BRONZE_HUNTER_BOOTS": {
    "perUnit": 100000,
    "npc": "ODGER"
  },
  "STARTER_LAVA_ROD": {
    "perUnit": 10000,
    "npc": "ODGER"
  },
  "ODGERS_SILVER_TOOTH": {
    "perUnit": 500000,
    "npc": "ODGER"
  },
  "SILVER_HUNTER_HELMET": {
    "perUnit": 500000,
    "npc": "ODGER"
  },
  "SILVER_HUNTER_CHESTPLATE": {
    "perUnit": 500000,
    "npc": "ODGER"
  },
  "SILVER_HUNTER_LEGGINGS": {
    "perUnit": 500000,
    "npc": "ODGER"
  },
  "SILVER_HUNTER_BOOTS": {
    "perUnit": 500000,
    "npc": "ODGER"
  },
  "BRONZE_TROPHY_FISHING_SACK": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "ODGERS_GOLD_TOOTH": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "GOLD_HUNTER_HELMET": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "GOLD_HUNTER_CHESTPLATE": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "GOLD_HUNTER_LEGGINGS": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "GOLD_HUNTER_BOOTS": {
    "perUnit": 1000000,
    "npc": "ODGER"
  },
  "SILVER_TROPHY_FISHING_SACK": {
    "perUnit": 5000000,
    "npc": "ODGER"
  },
  "ODGERS_DIAMOND_TOOTH": {
    "perUnit": 2500000,
    "npc": "ODGER"
  },
  "DIAMOND_HUNTER_HELMET": {
    "perUnit": 2500000,
    "npc": "ODGER"
  },
  "DIAMOND_HUNTER_CHESTPLATE": {
    "perUnit": 2500000,
    "npc": "ODGER"
  },
  "DIAMOND_HUNTER_LEGGINGS": {
    "perUnit": 2500000,
    "npc": "ODGER"
  },
  "DIAMOND_HUNTER_BOOTS": {
    "perUnit": 2500000,
    "npc": "ODGER"
  },
  "UNDEAD_BOW": {
    "perUnit": 80000,
    "npc": "OPHELIA"
  },
  "DARK_GOGGLES": {
    "perUnit": 80000,
    "npc": "OPHELIA"
  },
  "MENDER_HELMET": {
    "perUnit": 80000,
    "npc": "OPHELIA"
  },
  "SUPERBOOM_TNT": {
    "perUnit": 2500,
    "npc": "WALTER"
  },
  "STONE_CHESTPLATE": {
    "perUnit": 80000,
    "npc": "OPHELIA"
  },
  "ENDER_STONE": {
    "perUnit": 10,
    "npc": "PEARL_DEALER"
  },
  "OBSIDIAN": {
    "perUnit": 50,
    "npc": "PEARL_DEALER"
  },
  "SILENT_PEARL": {
    "perUnit": 1250,
    "npc": "PEARL_DEALER"
  },
  "REMNANT_OF_THE_EYE": {
    "perUnit": 200000,
    "npc": "PEARL_DEALER"
  },
  "STONK_PICKAXE": {
    "perUnit": 499999,
    "npc": "PEARL_DEALER"
  },
  "FLINT": {
    "perUnit": 6,
    "npc": "PAT"
  },
  "SHINY_ORB": {
    "perUnit": 5000,
    "npc": "PIG_SHOP"
  },
  "TRUE_ESSENCE": {
    "perUnit": 25000,
    "npc": "OLD_SHAMAN_NYKO"
  },
  "PLUMBER_SPONGE": {
    "perUnit": 50,
    "npc": "PLUMBER_JOE"
  },
  "SUPER_SCRUBBER": {
    "perUnit": 25000,
    "npc": "PLUMBER_JOE"
  },
  "IRON_HELMET": {
    "perUnit": 15,
    "npc": "ROSETTA"
  },
  "IRON_CHESTPLATE": {
    "perUnit": 25,
    "npc": "ROSETTA"
  },
  "IRON_LEGGINGS": {
    "perUnit": 30,
    "npc": "ROSETTA"
  },
  "IRON_BOOTS": {
    "perUnit": 20,
    "npc": "ROSETTA"
  },
  "ROSETTA_HELMET": {
    "perUnit": 1050,
    "npc": "ROSETTA"
  },
  "ROSETTA_CHESTPLATE": {
    "perUnit": 1320,
    "npc": "ROSETTA"
  },
  "ROSETTA_LEGGINGS": {
    "perUnit": 1200,
    "npc": "ROSETTA"
  },
  "ROSETTA_BOOTS": {
    "perUnit": 960,
    "npc": "ROSETTA"
  },
  "SQUIRE_HELMET": {
    "perUnit": 5000,
    "npc": "ROSETTA"
  },
  "SQUIRE_CHESTPLATE": {
    "perUnit": 8000,
    "npc": "ROSETTA"
  },
  "SQUIRE_LEGGINGS": {
    "perUnit": 7000,
    "npc": "ROSETTA"
  },
  "SQUIRE_BOOTS": {
    "perUnit": 4000,
    "npc": "ROSETTA"
  },
  "SQUIRE_SWORD": {
    "perUnit": 5000,
    "npc": "ROSETTA"
  },
  "MERCENARY_HELMET": {
    "perUnit": 35000,
    "npc": "ROSETTA"
  },
  "MERCENARY_CHESTPLATE": {
    "perUnit": 70000,
    "npc": "ROSETTA"
  },
  "MERCENARY_LEGGINGS": {
    "perUnit": 45000,
    "npc": "ROSETTA"
  },
  "MERCENARY_BOOTS": {
    "perUnit": 30000,
    "npc": "ROSETTA"
  },
  "MERCENARY_AXE": {
    "perUnit": 30000,
    "npc": "ROSETTA"
  },
  "CELESTE_HELMET": {
    "perUnit": 5000,
    "npc": "ROSETTA"
  },
  "CELESTE_CHESTPLATE": {
    "perUnit": 8000,
    "npc": "ROSETTA"
  },
  "CELESTE_LEGGINGS": {
    "perUnit": 7000,
    "npc": "ROSETTA"
  },
  "CELESTE_BOOTS": {
    "perUnit": 4000,
    "npc": "ROSETTA"
  },
  "CELESTE_WAND": {
    "perUnit": 5000,
    "npc": "ROSETTA"
  },
  "STARLIGHT_HELMET": {
    "perUnit": 35000,
    "npc": "ROSETTA"
  },
  "STARLIGHT_CHESTPLATE": {
    "perUnit": 70000,
    "npc": "ROSETTA"
  },
  "STARLIGHT_LEGGINGS": {
    "perUnit": 45000,
    "npc": "ROSETTA"
  },
  "STARLIGHT_BOOTS": {
    "perUnit": 30000,
    "npc": "ROSETTA"
  },
  "STARLIGHT_WAND": {
    "perUnit": 30000,
    "npc": "ROSETTA"
  },
  "FORAGING_FORTUNE_BOOSTER": {
    "perUnit": 50000,
    "npc": "SAWYER"
  },
  "SNOW_SHOVEL": {
    "perUnit": 2500,
    "npc": "SCOOP"
  },
  "CHEAP_TUXEDO_CHESTPLATE": {
    "perUnit": 1000000,
    "npc": "SEYMOUR"
  },
  "CHEAP_TUXEDO_LEGGINGS": {
    "perUnit": 1000000,
    "npc": "SEYMOUR"
  },
  "CHEAP_TUXEDO_BOOTS": {
    "perUnit": 1000000,
    "npc": "SEYMOUR"
  },
  "FANCY_TUXEDO_CHESTPLATE": {
    "perUnit": 6666666,
    "npc": "SEYMOUR"
  },
  "FANCY_TUXEDO_LEGGINGS": {
    "perUnit": 6666666,
    "npc": "SEYMOUR"
  },
  "FANCY_TUXEDO_BOOTS": {
    "perUnit": 6666666,
    "npc": "SEYMOUR"
  },
  "ELEGANT_TUXEDO_CHESTPLATE": {
    "perUnit": 24999999,
    "npc": "SEYMOUR"
  },
  "ELEGANT_TUXEDO_LEGGINGS": {
    "perUnit": 24999999,
    "npc": "SEYMOUR"
  },
  "ELEGANT_TUXEDO_BOOTS": {
    "perUnit": 24999999,
    "npc": "SEYMOUR"
  },
  "FESTIVE_SINKER": {
    "perUnit": 40000,
    "npc": "SHERRY"
  },
  "ICE_BAIT": {
    "perUnit": 12,
    "npc": "SHERRY"
  },
  "BOTTLE_OF_JYRRE": {
    "perUnit": 50000,
    "npc": "SHERRY"
  },
  "FROSTY_SNOW_BALL": {
    "perUnit": 75000,
    "npc": "SHERRY"
  },
  "ICE": {
    "perUnit": 1,
    "npc": "SHERRY"
  },
  "PACKED_ICE": {
    "perUnit": 9,
    "npc": "SHERRY"
  },
  "LARGE_WINTER_SACK": {
    "perUnit": 250000,
    "npc": "SHERRY"
  },
  "MOIL_LOG": {
    "perUnit": 50000,
    "npc": "SMITHMONGER"
  },
  "DIRT_BOTTLE": {
    "perUnit": 100000,
    "npc": "SMITHMONGER"
  },
  "TOIL_LOG": {
    "perUnit": 1000000,
    "npc": "SMITHMONGER"
  },
  "REFINED_AMBER": {
    "perUnit": 1000000,
    "npc": "SMITHMONGER"
  },
  "BLESSED_FRUIT": {
    "perUnit": 1000000,
    "npc": "SMITHMONGER"
  },
  "SAM_SCYTHE": {
    "perUnit": 2000,
    "npc": "SKYMART"
  },
  "HYDRO_CAN_1000": {
    "perUnit": 5000,
    "npc": "SKYMART"
  },
  "PORTABLE_WASHER": {
    "perUnit": 20000,
    "npc": "SKYMART"
  },
  "SKYMART_VACUUM": {
    "perUnit": 5000,
    "npc": "SKYMART"
  },
  "TUTTI_FRUTTI_POISON": {
    "perUnit": 850,
    "npc": "SHIFTY"
  },
  "DR_PAPER": {
    "perUnit": 3400,
    "npc": "SHIFTY"
  },
  "SLAYER_ENERGY_DRINK": {
    "perUnit": 8500,
    "npc": "SHIFTY"
  },
  "ABIPHONE_X_PLUS": {
    "perUnit": 500000,
    "npc": "UDEL"
  },
  "ABIPHONE_X_PLUS_SPECIAL_EDITION": {
    "perUnit": 500000,
    "npc": "UDEL"
  },
  "ABIPHONE_XI_ULTRA": {
    "perUnit": 500000,
    "npc": "UDEL"
  },
  "ABIPHONE_XI_ULTRA_STYLE": {
    "perUnit": 500000,
    "npc": "UDEL"
  },
  "ABIPHONE_XII_MEGA": {
    "perUnit": 1000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XII_MEGA_COLOR": {
    "perUnit": 1000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XIII_PRO": {
    "perUnit": 5000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XIII_PRO_GIGA": {
    "perUnit": 5000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XIV_ENORMOUS_BLACK": {
    "perUnit": 25000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XIV_ENORMOUS": {
    "perUnit": 25000000,
    "npc": "UDEL"
  },
  "ABIPHONE_XIV_ENORMOUS_PURPLE": {
    "perUnit": 25000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_DRAGON": {
    "perUnit": 50000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_NUCLEUS": {
    "perUnit": 50000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_VOLCANO": {
    "perUnit": 50000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_PLUS_LUNAR": {
    "perUnit": 100000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_PLUS_FLOWER": {
    "perUnit": 100000000,
    "npc": "UDEL"
  },
  "ABIPHONE_FLIP_PLUS_CLOCKWORK": {
    "perUnit": 100000000,
    "npc": "UDEL"
  },
  "MYCEL": {
    "perUnit": 20,
    "npc": "ULYN"
  },
  "BOO_STONE": {
    "perUnit": 10000,
    "npc": "TYASHOI_ALCHEMIST"
  },
  "GREAT_SPOOK_POTION": {
    "perUnit": 20000,
    "npc": "TYASHOI_ALCHEMIST"
  },
  "REVIVE_STONE": {
    "perUnit": 100000,
    "npc": "WINONA"
  },
  "PET_ITEM_ALL_SKILLS_BOOST_COMMON": {
    "perUnit": 50000,
    "npc": "ZOG"
  },
  "PET_ITEM_FARMING_SKILL_BOOST_COMMON": {
    "perUnit": 60000,
    "npc": "ZOG"
  },
  "PET_ITEM_FISHING_SKILL_BOOST_COMMON": {
    "perUnit": 60000,
    "npc": "ZOG"
  },
  "PET_ITEM_FORAGING_SKILL_BOOST_COMMON": {
    "perUnit": 60000,
    "npc": "ZOG"
  },
  "PET_ITEM_MINING_SKILL_BOOST_COMMON": {
    "perUnit": 60000,
    "npc": "ZOG"
  },
  "PET_ITEM_COMBAT_SKILL_BOOST_COMMON": {
    "perUnit": 60000,
    "npc": "ZOG"
  },
  "PET_ITEM_MINING_SKILL_BOOST_UNCOMMON": {
    "perUnit": 250000,
    "npc": "ZOG"
  },
  "PET_ITEM_FARMING_SKILL_BOOST_RARE": {
    "perUnit": 500000,
    "npc": "ZOG"
  },
  "PET_ITEM_BIG_TEETH_COMMON": {
    "perUnit": 750000,
    "npc": "ZOG"
  },
  "PET_ITEM_IRON_CLAWS_COMMON": {
    "perUnit": 750000,
    "npc": "ZOG"
  },
  "PET_ITEM_HARDENED_SCALES_UNCOMMON": {
    "perUnit": 1000000,
    "npc": "ZOG"
  },
  "PET_ITEM_SHARPENED_CLAWS_UNCOMMON": {
    "perUnit": 1000000,
    "npc": "ZOG"
  },
  "PET_ITEM_BUBBLEGUM": {
    "perUnit": 5000000,
    "npc": "ZOG"
  },
  "GENERAL_MEDALLION": {
    "perUnit": 1000000,
    "npc": "ZODD"
  },
  "STAINED_CLAY-1": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-2": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-3": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-4": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-5": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-6": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-7": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-8": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-9": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-10": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-11": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-12": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-13": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-14": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_CLAY-15": {
    "perUnit": 8,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-1": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-2": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-3": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-4": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-5": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-6": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-7": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-8": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-9": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-10": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-11": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-12": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-13": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-14": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS_PANE-15": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-1": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-2": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-3": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-4": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-5": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-6": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-7": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-8": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-9": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-10": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-11": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-12": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-13": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-14": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "STAINED_GLASS-15": {
    "perUnit": 16,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-1": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-2": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-3": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-4": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-5": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-6": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-7": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-8": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-9": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-10": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-11": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-12": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-13": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-14": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "CARPET-15": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-1": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-2": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-3": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-4": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-5": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-6": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-7": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-8": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-9": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-10": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-11": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-12": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-13": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-14": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "WOOL-15": {
    "perUnit": 32,
    "npc": "WOOL_WEAVER"
  },
  "UNDEAD_SWORD": {
    "perUnit": 100,
    "npc": "WEAPONSMITH"
  },
  "END_SWORD": {
    "perUnit": 150,
    "npc": "WEAPONSMITH"
  },
  "SPIDER_SWORD": {
    "perUnit": 100,
    "npc": "WEAPONSMITH"
  },
  "ROGUE_SWORD": {
    "perUnit": 100,
    "npc": "WEAPONSMITH"
  },
  "BOW": {
    "perUnit": 25,
    "npc": "WEAPONSMITH"
  },
  "WITHER_BOW": {
    "perUnit": 250,
    "npc": "WEAPONSMITH"
  },
  "ARTISANAL_SHORTBOW": {
    "perUnit": 600,
    "npc": "WEAPONSMITH"
  }
};

// ---- Express 应用（内联自 server/index.js）----








const app = express();
// FC_SERVER_PORT 由阿里云 FC 自定义运行时注入，Express 监听该端口接收平台转发来的请求
const PORT = process.env.FC_SERVER_PORT || process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// EdgeOne Makers 云函数把 /api/* 转发给函数时剥离 /api 前缀（函数内 req.url 为 /status 等），
// 这里补回前缀，让下方 /api/xxx 路由能正常匹配
if (process.env.IS_FC) {
  app.use((req, res, next) => {
    if (!req.url.startsWith('/api')) req.url = '/api' + req.url;
    next();
  });
}

// static served by EdgeOne Pages

// Configuration - API Key should be set via environment variable
// Get your API key from https://hypixel.net/developer
const API_KEY = process.env.HYPIXEL_API_KEY || '';
const HYPIXEL_API_BASE = 'https://api.hypixel.net/v2';
const USE_MOCK_DATA = !API_KEY; // Use mock data if no API key

// Cache for Bazaar data
let bazaarCache = {
  data: null,
  lastUpdated: null
};
const CACHE_DURATION = 60 * 1000; // 1 minute cache

// Format product data for frontend
function formatProduct(productId, product) {
  const quickStatus = product.quick_status;
  const npc = npcPrices[productId];
  return {
    id: productId,
    name: formatProductName(productId),
    buyPrice: Math.round((quickStatus.buyPrice || 0) * 100) / 100,
    sellPrice: Math.round((quickStatus.sellPrice || 0) * 100) / 100,
    buyOrders: quickStatus.buyOrders || 0,
    sellOrders: quickStatus.sellOrders || 0,
    buyVolume: quickStatus.buyVolume || 0,
    sellVolume: quickStatus.sellVolume || 0,
    npcBuyPrice: npc ? npc.perUnit : null,
    npcSource: npc ? npc.npc : null,
    history: product.history || []
  };
}

// 带数据值（:N 后缀）商品的正确名称，避免被通用格式化拆成 "Sand: 1" 之类的错名
const PRODUCT_NAME_OVERRIDES = {
  'SAND:1': 'Red Sand',
  'LOG:1': 'Spruce Log',
  'LOG:2': 'Birch Log',
  'LOG:3': 'Jungle Log',
  'LOG_2': 'Acacia Log',
  'LOG_2:1': 'Dark Oak Log',
  'INK_SACK:3': 'Cocoa Beans',
  'INK_SACK:4': 'Lapis Lazuli',
  'RAW_FISH:1': 'Raw Salmon',
  'RAW_FISH:2': 'Raw Clownfish',
  'RAW_FISH:3': 'Pufferfish'
};

// Format product ID to readable name
function formatProductName(productId) {
  if (PRODUCT_NAME_OVERRIDES[productId]) return PRODUCT_NAME_OVERRIDES[productId];
  return productId
    .replace(/_/g, ' ')
    .replace(/(\d+)/g, ' $1')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

// Generate realistic mock Bazaar data with history
function generateMockData() {
  const mockProducts = {
    'ENCHANTED_DIAMOND': { buyPrice: 12500, sellPrice: 10200, buyVolume: 150000, sellVolume: 180000, buyOrders: 45, sellOrders: 120 },
    'ENCHANTED_GOLD': { buyPrice: 2800, sellPrice: 2400, buyVolume: 320000, sellVolume: 350000, buyOrders: 89, sellOrders: 210 },
    'ENCHANTED_IRON': { buyPrice: 450, sellPrice: 380, buyVolume: 890000, sellVolume: 920000, buyOrders: 230, sellOrders: 450 },
    'ENCHANTED_COAL': { buyPrice: 180, sellPrice: 150, buyVolume: 1200000, sellVolume: 1150000, buyOrders: 520, sellOrders: 680 },
    'ENCHANTED_REDSTONE': { buyPrice: 95, sellPrice: 78, buyVolume: 980000, sellVolume: 1020000, buyOrders: 380, sellOrders: 420 },
    'ENCHANTED_LAPIS_LAZULI': { buyPrice: 220, sellPrice: 185, buyVolume: 750000, sellVolume: 780000, buyOrders: 290, sellOrders: 350 },
    'ENCHANTED_EMERALD': { buyPrice: 18500, sellPrice: 15200, buyVolume: 85000, sellVolume: 92000, buyOrders: 28, sellOrders: 65 },
    'ENCHANTED_DIAMOND_BLOCK': { buyPrice: 112000, sellPrice: 98000, buyVolume: 12000, sellVolume: 15000, buyOrders: 8, sellOrders: 22 },
    'ENCHANTED_GOLD_BLOCK': { buyPrice: 25000, sellPrice: 22000, buyVolume: 28000, sellVolume: 32000, buyOrders: 15, sellOrders: 35 },
    'DRAGON_BREATH': { buyPrice: 180, sellPrice: 145, buyVolume: 450000, sellVolume: 480000, buyOrders: 180, sellOrders: 250 },
    'ELDER_GUARDIAN_CONSUME': { buyPrice: 8500, sellPrice: 7200, buyVolume: 8500, sellVolume: 9200, buyOrders: 12, sellOrders: 18 },
    'GUARDIAN_FEATHER': { buyPrice: 1450, sellPrice: 1200, buyVolume: 45000, sellVolume: 52000, buyOrders: 35, sellOrders: 55 },
    'SHARK_FIN': { buyPrice: 3800, sellPrice: 3200, buyVolume: 28000, sellVolume: 32000, buyOrders: 22, sellOrders: 38 },
    'WHALE_BAIT': { buyPrice: 950, sellPrice: 780, buyVolume: 65000, sellVolume: 72000, buyOrders: 48, sellOrders: 72 },
    'MAGMA_CREAM': { buyPrice: 280, sellPrice: 220, buyVolume: 680000, sellVolume: 720000, buyOrders: 320, sellOrders: 450 },
    'ROSE_RED': { buyPrice: 85, sellPrice: 65, buyVolume: 520000, sellVolume: 550000, buyOrders: 280, sellOrders: 320 },
    'OXEYE_DAISY': { buyPrice: 280, sellPrice: 220, buyVolume: 180000, sellVolume: 210000, buyOrders: 95, sellOrders: 140 },
    'WITHER_SKELETON_SKULL': { buyPrice: 4200, sellPrice: 3500, buyVolume: 15000, sellVolume: 18000, buyOrders: 18, sellOrders: 28 },
    'WITHER_ROSE': { buyPrice: 1800, sellPrice: 1500, buyVolume: 35000, sellVolume: 42000, buyOrders: 25, sellOrders: 42 },
    'SLIME_BALL': { buyPrice: 145, sellPrice: 115, buyVolume: 420000, sellVolume: 450000, buyOrders: 240, sellOrders: 320 },
    'RABBIT_FOOT': { buyPrice: 380, sellPrice: 310, buyVolume: 120000, sellVolume: 140000, buyOrders: 75, sellOrders: 105 },
    'SPIDER_EYE': { buyPrice: 85, sellPrice: 65, buyVolume: 380000, sellVolume: 420000, buyOrders: 220, sellOrders: 280 },
    'FERMENTED_SPIDER_EYE': { buyPrice: 420, sellPrice: 350, buyVolume: 95000, sellVolume: 110000, buyOrders: 58, sellOrders: 82 },
    'BLAZE_ROD': { buyPrice: 680, sellPrice: 550, buyVolume: 220000, sellVolume: 250000, buyOrders: 145, sellOrders: 190 },
    'BLAZE_POWDER': { buyPrice: 380, sellPrice: 310, buyVolume: 180000, sellVolume: 210000, buyOrders: 110, sellOrders: 155 },
    'GHAST_TEAR': { buyPrice: 1850, sellPrice: 1500, buyVolume: 28000, sellVolume: 35000, buyOrders: 22, sellOrders: 35 },
    'NETHER_WART': { buyPrice: 45, sellPrice: 35, buyVolume: 850000, sellVolume: 920000, buyOrders: 480, sellOrders: 580 },
    'POTION_ENCHANTED_GOLDEN_APPLE': { buyPrice: 55000, sellPrice: 48000, buyVolume: 2500, sellVolume: 3200, buyOrders: 5, sellOrders: 12 },
    'ENCHANTED_GOLDEN_APPLE': { buyPrice: 85000, sellPrice: 72000, buyVolume: 1800, sellVolume: 2400, buyOrders: 4, sellOrders: 8 },
    'TIGHTLY_TIED_HONEY_BOTTLE': { buyPrice: 18500, sellPrice: 15500, buyVolume: 12000, sellVolume: 15000, buyOrders: 10, sellOrders: 18 },
    'HOG_FISH': { buyPrice: 145, sellPrice: 115, buyVolume: 280000, sellVolume: 320000, buyOrders: 165, sellOrders: 210 },
    'SNOW_BALL': { buyPrice: 25, sellPrice: 18, buyVolume: 1200000, sellVolume: 1350000, buyOrders: 650, sellOrders: 780 },
    'ICE': { buyPrice: 85, sellPrice: 65, buyVolume: 420000, sellVolume: 480000, buyOrders: 250, sellOrders: 320 },
    'PACKED_ICE': { buyPrice: 180, sellPrice: 145, buyVolume: 280000, sellVolume: 320000, buyOrders: 165, sellOrders: 220 },
    'PRISMARINE_SHARD': { buyPrice: 95, sellPrice: 75, buyVolume: 380000, sellVolume: 420000, buyOrders: 220, sellOrders: 280 },
    'PRISMARINE_CRYSTALS': { buyPrice: 320, sellPrice: 260, buyVolume: 150000, sellVolume: 180000, buyOrders: 95, sellOrders: 135 },
    'SEA_LANTERN': { buyPrice: 1450, sellPrice: 1200, buyVolume: 55000, sellVolume: 65000, buyOrders: 42, sellOrders: 65 },
    'TARANTULA_WEB': { buyPrice: 180, sellPrice: 145, buyVolume: 280000, sellVolume: 320000, buyOrders: 175, sellOrders: 230 },
    'FLYING_FISH': { buyPrice: 420, sellPrice: 350, buyVolume: 85000, sellVolume: 100000, buyOrders: 55, sellOrders: 78 },
    'GOLDEN_DRAGON_EGG': { buyPrice: 25000000, sellPrice: 22000000, buyVolume: 5, sellVolume: 8, buyOrders: 2, sellOrders: 3 },
    'TITANIUM': { buyPrice: 18500, sellPrice: 15500, buyVolume: 15000, sellVolume: 18000, buyOrders: 12, sellOrders: 20 },
    'AUGURITE': { buyPrice: 4200, sellPrice: 3500, buyVolume: 25000, sellVolume: 30000, buyOrders: 18, sellOrders: 28 },
    'BERBERIS': { buyPrice: 850, sellPrice: 700, buyVolume: 45000, sellVolume: 55000, buyOrders: 32, sellOrders: 48 },
    'SINTEA': { buyPrice: 680, sellPrice: 550, buyVolume: 62000, sellVolume: 75000, buyOrders: 45, sellOrders: 62 },
    'JUTE': { buyPrice: 145, sellPrice: 115, buyVolume: 180000, sellVolume: 220000, buyOrders: 115, sellOrders: 155 },
    'RICE': { buyPrice: 180, sellPrice: 145, buyVolume: 150000, sellVolume: 180000, buyOrders: 95, sellOrders: 130 },
    'PEONY': { buyPrice: 220, sellPrice: 175, buyVolume: 95000, sellVolume: 115000, buyOrders: 65, sellOrders: 88 },
    'VANILLA': { buyPrice: 950, sellPrice: 780, buyVolume: 55000, sellVolume: 68000, buyOrders: 38, sellOrders: 52 },
    'COMPRESSED_OBSIDIAN': { buyPrice: 4800, sellPrice: 4000, buyVolume: 35000, sellVolume: 42000, buyOrders: 25, sellOrders: 38 },
    'POWER_CRYSTAL': { buyPrice: 8500, sellPrice: 7200, buyVolume: 18000, sellVolume: 22000, buyOrders: 14, sellOrders: 22 },
    'CELL_CASE': { buyPrice: 1450, sellPrice: 1200, buyVolume: 65000, sellVolume: 78000, buyOrders: 42, sellOrders: 58 },
    'REACTOR_ARTIFACT': { buyPrice: 18500, sellPrice: 15500, buyVolume: 8500, sellVolume: 10500, buyOrders: 8, sellOrders: 14 },
    'NULL_OVOID': { buyPrice: 2200, sellPrice: 1850, buyVolume: 42000, sellVolume: 52000, buyOrders: 28, sellOrders: 42 },
    'GRIFFIN_FEATHER': { buyPrice: 4200, sellPrice: 3500, buyVolume: 25000, sellVolume: 32000, buyOrders: 18, sellOrders: 28 },
    'KISMET_FEATHER': { buyPrice: 6800, sellPrice: 5800, buyVolume: 15000, sellVolume: 18000, buyOrders: 12, sellOrders: 18 },
    'KELLERMAN_SLATE': { buyPrice: 1800, sellPrice: 1500, buyVolume: 55000, sellVolume: 65000, buyOrders: 38, sellOrders: 52 },
    'DARK_ORB': { buyPrice: 6500, sellPrice: 5500, buyVolume: 22000, sellVolume: 28000, buyOrders: 16, sellOrders: 25 },
    'WITHER_CATALYST': { buyPrice: 125000, sellPrice: 105000, buyVolume: 1800, sellVolume: 2200, buyOrders: 3, sellOrders: 5 },
    'SOUL_WHIP': { buyPrice: 85000, sellPrice: 72000, buyVolume: 2500, sellVolume: 3200, buyOrders: 4, sellOrders: 7 },
    'HYPER_CATALYST_UPGRADER': { buyPrice: 12000000, sellPrice: 10000000, buyVolume: 25, sellVolume: 35, buyOrders: 1, sellOrders: 2 },
    'PERFECT_CUT_GEM': { buyPrice: 8500000, sellPrice: 7200000, buyVolume: 45, sellVolume: 58, buyOrders: 1, sellOrders: 2 },
    'JASPER_GEM': { buyPrice: 5500000, sellPrice: 4800000, buyVolume: 85, sellVolume: 105, buyOrders: 2, sellOrders: 3 },
    'TOPAZ_GEM': { buyPrice: 3200000, sellPrice: 2800000, buyVolume: 120, sellVolume: 155, buyOrders: 2, sellOrders: 3 },
    'SAPPHIRE_GEM': { buyPrice: 4200000, sellPrice: 3600000, buyVolume: 95, sellVolume: 120, buyOrders: 2, sellOrders: 3 },
    'RUBY_GEM': { buyPrice: 5500000, sellPrice: 4800000, buyVolume: 85, sellVolume: 105, buyOrders: 2, sellOrders: 3 },
    'AMETHYST_GEM': { buyPrice: 6500000, sellPrice: 5500000, buyVolume: 75, sellVolume: 95, buyOrders: 2, sellOrders: 3 },
    'JADE_GEM': { buyPrice: 4800000, sellPrice: 4200000, buyVolume: 95, sellVolume: 120, buyOrders: 2, sellOrders: 3 },
    'AMBER_GEM': { buyPrice: 3800000, sellPrice: 3200000, buyVolume: 110, sellVolume: 145, buyOrders: 2, sellOrders: 3 }
  };

  const result = {};
  const now = Date.now();

  for (const [id, data] of Object.entries(mockProducts)) {
    // Generate random historical data points (last 7 days)
    const history = [];
    for (let i = 168; i >= 0; i--) {
      const hourAgo = now - (i * 60 * 60 * 1000);
      const randomVariation = (Math.random() - 0.5) * 0.2;
      const buyPrice = Math.round(data.buyPrice * (1 + randomVariation));
      const sellPrice = Math.round(data.sellPrice * (1 + randomVariation));

      history.push({
        timestamp: new Date(hourAgo).toISOString(),
        buyPrice,
        sellPrice,
        buyOrders: data.buyOrders + Math.floor(Math.random() * 20 - 10),
        sellOrders: data.sellOrders + Math.floor(Math.random() * 30 - 15)
      });
    }

    result[id] = {
      product_id: id,
      quick_status: {
        buyPrice: data.buyPrice,
        sellPrice: data.sellPrice,
        buyVolume: data.buyVolume,
        sellVolume: data.sellVolume,
        buyOrders: data.buyOrders,
        sellOrders: data.sellOrders,
        buyMovingWeek: Math.floor(data.buyVolume * 0.25),
        sellMovingWeek: Math.floor(data.sellVolume * 0.25)
      },
      history: history
    };
  }
  return result;
}

// Fetch Bazaar data from Hypixel API
async function fetchBazaarData() {
  // Use mock data if no API key configured
  if (USE_MOCK_DATA) {
    return generateMockData();
  }

  // Check cache first
  if (bazaarCache.data && bazaarCache.lastUpdated) {
    const timeSinceUpdate = Date.now() - bazaarCache.lastUpdated;
    if (timeSinceUpdate < CACHE_DURATION) {
      return bazaarCache.data;
    }
  }

  try {
    const response = await axios.get(`${HYPIXEL_API_BASE}/skyblock/bazaar`, {
      headers: {
        'API-Key': API_KEY
      },
      timeout: 10000
    });

    if (response.data.success) {
      bazaarCache.data = response.data.products;
      bazaarCache.lastUpdated = Date.now();
      return bazaarCache.data;
    } else {
      throw new Error('Failed to fetch Bazaar data from Hypixel API');
    }
  } catch (error) {
    console.error('Error fetching Bazaar data:', error.message);
    // Return cached data if available
    if (bazaarCache.data) {
      return bazaarCache.data;
    }
    throw error;
  }
}

// API Routes

// Get all products
app.get('/api/products', async (req, res) => {
  try {
    const products = await fetchBazaarData();
    const formatted = Object.entries(products).map(([id, data]) => formatProduct(id, data));

    // Sort by buy volume (most popular first)
    formatted.sort((a, b) => b.buyVolume - a.buyVolume);

    res.json({
      success: true,
      data: formatted,
      lastUpdated: bazaarCache.lastUpdated
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

// Get single product details
app.get('/api/product/:id', async (req, res) => {
  try {
    const productId = req.params.id.toUpperCase();
    const products = await fetchBazaarData();

    if (!products[productId]) {
      return res.status(404).json({
        success: false,
        error: 'Product not found'
      });
    }

    const product = products[productId];
    const formatted = formatProduct(productId, product);

    // Only use file history if no history in product data (real API mode)
    if (!formatted.history || formatted.history.length === 0) {
      formatted.history = dataStore.getHistory(productId);
    }

    res.json({
      success: true,
      data: formatted
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

// Get product history
app.get('/api/history/:id', (req, res) => {
  const productId = req.params.id.toUpperCase();
  const history = dataStore.getHistory(productId);

  res.json({
    success: true,
    data: history
  });
});

// Get favorites
app.get('/api/favorites', (req, res) => {
  const favorites = dataStore.getFavorites();
  res.json({
    success: true,
    data: favorites
  });
});

// Add to favorites
app.post('/api/favorites/:id', (req, res) => {
  const productId = req.params.id.toUpperCase();
  const favorites = dataStore.addFavorite(productId);

  res.json({
    success: true,
    data: favorites
  });
});

// Remove from favorites
app.delete('/api/favorites/:id', (req, res) => {
  const productId = req.params.id.toUpperCase();
  const favorites = dataStore.removeFavorite(productId);

  res.json({
    success: true,
    data: favorites
  });
});

// Export data
app.get('/api/export', (req, res) => {
  const format = req.query.format || 'json';

  if (format === 'csv') {
    const csv = dataStore.exportAsCSV();
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename=bazaar_history.csv');
    res.send(csv);
  } else {
    const data = dataStore.getAllHistory();
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', 'attachment; filename=bazaar_history.json');
    res.json(data);
  }
});

// Get cache status
app.get('/api/status', (req, res) => {
  res.json({
    success: true,
    data: {
      lastUpdated: bazaarCache.lastUpdated,
      hasApiKey: !!API_KEY,
      usingMockData: USE_MOCK_DATA
    }
  });
});

// Manual trigger to save history now
app.post('/api/save-history', async (req, res) => {
  try {
    const products = await fetchBazaarData();
    const popularProducts = Object.entries(products)
      .sort((a, b) => {
        const aVol = a[1].quick_status?.buyVolume || 0;
        const bVol = b[1].quick_status?.buyVolume || 0;
        return bVol - aVol;
      })
      .slice(0, 50);

    for (const [id, data] of popularProducts) {
      dataStore.saveToHistory(id, {
        buyPrice: data.quick_status?.buyPrice || 0,
        sellPrice: data.quick_status?.sellPrice || 0,
        buyOrders: data.quick_status?.buyOrders || 0,
        sellOrders: data.quick_status?.sellOrders || 0
      });
    }

    res.json({ success: true, message: 'History saved for ' + popularProducts.length + ' products' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Start background task to save history periodically
// (skipped on serverless platforms: no long-running process and read-only filesystem)
if (!process.env.VERCEL && !process.env.IS_FC) setInterval(async () => {
  try {
    const products = await fetchBazaarData();
    // Save a sample of popular products to history
    const popularProducts = Object.entries(products)
      .sort((a, b) => {
        const aVol = a[1].quick_status?.buyVolume || 0;
        const bVol = b[1].quick_status?.buyVolume || 0;
        return bVol - aVol;
      })
      .slice(0, 50); // Save top 50 products

    for (const [id, data] of popularProducts) {
      dataStore.saveToHistory(id, {
        buyPrice: data.quick_status?.buyPrice || 0,
        sellPrice: data.quick_status?.sellPrice || 0,
        buyOrders: data.quick_status?.buyOrders || 0,
        sellOrders: data.quick_status?.sellOrders || 0
      });
    }
    console.log('History saved at', new Date().toISOString());
  } catch (error) {
    console.error('Error saving history:', error.message);
  }
}, 5 * 60 * 1000); // Every 5 minutes

// Serve frontend for all other routes
app.get('*', (req, res) => {
  res.status(404).json({ success: false, error: 'Not found' });
});

// Start server (skipped on serverless platforms — the platform calls the exported app directly)
if (!process.env.VERCEL && !process.env.IS_FC) {
  app.listen(PORT, () => {
    console.log(`
╔═══════════════════════════════════════════════════╗
║     Skyblock Bazaar Monitor                       ║
║     Running on http://localhost:${PORT}               ║
╚═══════════════════════════════════════════════════╝
${USE_MOCK_DATA ? `
  📦 Using MOCK DATA (no API key configured)

  To use real data, get your API key from:
    https://hypixel.net/developer

  Then run:
    Windows: set HYPIXEL_API_KEY=your_key && npm start
    Linux/Mac: HYPIXEL_API_KEY=your_key npm start
` : `
  ✅ Connected to Hypixel API
`}
  `);
  });
}




export default app;
