// 生成自包含的 EdgeOne Makers 云函数入口 cloud-functions/api/[[default]].js
// EdgeOne 打包时只包含 cloud-functions/ 目录，仓库根目录的 server/、data/ 不会进部署包，
// 所以必须把 Express 应用、dataStore、npc 价格全部内联进入口文件，只保留 node_modules 依赖。
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const serverIndex = fs.readFileSync(path.join(root, 'server', 'index.js'), 'utf8');
const dataStoreSrc = fs.readFileSync(path.join(root, 'server', 'dataStore.js'), 'utf8');
const npcPricesJson = fs.readFileSync(path.join(root, 'data', 'npc-prices.json'), 'utf8');

// 去掉 server/index.js 顶部的 require 行（由入口统一提供）
let appCode = serverIndex;
for (const line of [
  "require('dotenv').config();",
  "const express = require('express');",
  "const axios = require('axios');",
  "const cors = require('cors');",
  "const path = require('path');",
  "const dataStore = require('./dataStore');",
  "const npcPrices = require('../data/npc-prices.json');",
]) {
  if (!appCode.includes(line)) {
    throw new Error('build-edgeone: 未找到待移除的 require 行: ' + line);
  }
  appCode = appCode.replace(line, '');
}

// 静态托管由 EdgeOne Pages 负责，函数内移除 express.static 与 SPA 兜底（它们依赖仓库根目录 public/）
const staticLine = "app.use(express.static(path.join(__dirname, '..', 'public')));";
if (!appCode.includes(staticLine)) {
  throw new Error('build-edgeone: 未找到 express.static 行');
}
appCode = appCode.replace(staticLine, '// static served by EdgeOne Pages');

if (!/app\.get\('\*'[\s\S]*?\n\}\)\s*;/.test(appCode)) {
  throw new Error('build-edgeone: 未找到 SPA 兜底路由');
}
appCode = appCode.replace(
  /app\.get\('\*'[\s\S]*?\n\}\)\s*;/,
  `app.get('*', (req, res) => {
  res.status(404).json({ success: false, error: 'Not found' });
});`
);

if (!appCode.includes('module.exports = app;')) {
  throw new Error('build-edgeone: 未找到 module.exports = app');
}
appCode = appCode.replace('module.exports = app;', '');

const output = `// AUTO-GENERATED by scripts/build-edgeone.js —— 勿手动修改
// EdgeOne Makers 云函数只打包 cloud-functions/ 目录，本文件自包含 server/dataStore/npc 价格
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);

// 复用 serverless 守卫：跳过 app.listen 和后台定时任务（server/index.js 检查该变量）
process.env.IS_FC = '1';

const path = require('path');
const express = require('express');
const axios = require('axios');
const cors = require('cors');
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---- dataStore（内联，含只读文件系统内存兜底）----
const dataStore = (() => {
  const module = { exports: {} };
${dataStoreSrc}
  return module.exports;
})();

// ---- NPC 价格（内联自 data/npc-prices.json）----
const npcPrices = ${npcPricesJson};

// ---- Express 应用（内联自 server/index.js）----
${appCode}

export default app;
`;

const outFile = path.join(root, 'cloud-functions', 'api', '[[default]].js');
fs.writeFileSync(outFile, output);
console.log('已生成', outFile, '(' + (output.length / 1024).toFixed(1) + ' KB)');
