// 生成自包含的 EdgeOne Makers 云函数入口 cloud-functions/api/[[default]].js
// EdgeOne 打包时只包含 cloud-functions/ 目录，且函数运行时不装 node_modules，
// 所以入口必须零依赖（仅 Node 内置 + 全局 fetch），并把 npc 价格数据内联进来。
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const appSrc = fs.readFileSync(path.join(root, 'cloud-functions', 'api', '_app.js'), 'utf8');
const npcPricesJson = fs.readFileSync(path.join(root, 'data', 'npc-prices.json'), 'utf8');

const output = `// AUTO-GENERATED by scripts/build-edgeone.js —— 勿手动修改（源码见 cloud-functions/api/_app.js）
// EdgeOne 云函数：官方 onRequest(context) → Response 模式，零依赖（Node 内置 + 全局 fetch）；npc 价格已内联

// ---- NPC 价格（内联自 data/npc-prices.json）----
const npcPrices = ${npcPricesJson};

// ---- 应用逻辑（内联自 cloud-functions/api/_app.js）----
${appSrc}

export { onRequest };
`;

const outFile = path.join(root, 'cloud-functions', 'api', '[[default]].js');
fs.writeFileSync(outFile, output);
console.log('已生成', outFile, '(' + (output.length / 1024).toFixed(1) + ' KB)');
